### ISSUE TITLE
skopeo 1.20.0 not copying layers.annotations when copying from containers-storage: to docker://

### ISSUE THREAD

**Issue by ver4a** [containers/skopeo#2686]
OS: Fedora Kinoite (with layers) 42.20250816.0
skopeo: 1.19.0/1.20.0 (rootless)
the image I'm copying is unmodified quay.io/fedora-ostree-desktops/kinoite:42

Problem: `layers.annotations` are dropped and digest changes on `skopeo copy` from `containers-storage:` to `docker://`, a direct copy from `docker://` to `docker://` preserves both annotations and layer digests.

If I copy an image containing layers with "annotations", their digest changes and "annotations" is removed
```bash
skopeo copy containers-storage:quay.io/fedora-ostree-desktops/kinoite:42 docker://registry.uncontrol.me/ver4a/onc-kde:42-upstream
```

Before copy
```bash
ver4a@laptop:~$ skopeo inspect containers-storage:quay.io/fedora-ostree-desktops/kinoite:42 --raw | jq | wc -l
537
```
[beforecopy.txt](https://github.com/user-attachments/files/22004701/beforecopy.txt)

After copy 
```bash
ver4a@laptop:~$ skopeo inspect docker://registry.uncontrol.me/ver4a/onc-kde:42-upstream --raw | jq | wc -l
345
```
[aftercopy.txt](https://github.com/user-attachments/files/22004671/aftercopy.txt)

When I try the same copy with --preserve-digests, I get this error
```bash
ver4a@laptop:~$ skopeo copy --preserve-digests containers-storage:quay.io/fedora-ostree-desktops/kinoite:42 docker://registry.uncontrol.me/ver4a/onc-kde:42-upstream
Getting image source signatures
FATA[0000] Copying this image would require changing layer representation, which we cannot do: "Instructed to preserve digests"
```
Here's a debug log with the first line containing environment removed [copy-preserve-log.txt](https://github.com/user-attachments/files/22004875/copy-preserve-log.txt)

The use case this breaks for me now is bootc upgrade/switch, bootc versions before 1.4.0 don't fail with this metadata disappearing, but newer versions do with an error `error: Switching: Pulling: Importing: Unencapsulating base: serialization error: invalid value: integer `-1`, expected u64` (I know that's related to a different repo, i put it here mainly for search engine indexing in case someone else hits it).

**Comment by GGh41th** [comment]
Hello @ver4a , i tried to understand why this was happening , and to avoid writing a huge comment , i will just provide the code snippets that matter , but i can provide a more detailed answer on how to get there.
The layers  are being copied using the copyLayers method in the single.go file in the image library , inside the copy package. (i refered to the single.go because there's only one image in the manifest index , otherwise we should consult the multiple.go instead). 
[single.go line 436 :](https://github.com/containers/image/blob/main/copy/single.go#L436)
```
// copyLayers copies layers from ic.src/ic.c.rawSource to dest, using and updating ic.manifestUpdates if necessary and ic.cannotModifyManifestReason == "".
func (ic *imageCopier) copyLayers(ctx context.Context) ([]compressiontypes.Algorithm, error) {
	srcInfos := ic.src.LayerInfos()
	updatedSrcInfos, err := ic.src.LayerInfosForCopy(ctx)
...
...
...
```
The LayerInfos and the LayerInfosForCopy methods will return a slice of structs of type BlobInfo , which hold these attributes (each element of the slice represent an image layer):

```
type BlobInfo struct {
	Digest      digest.Digest // "" if unknown.
	Size        int64         // -1 if unknown
	URLs        []string
	Annotations map[string]string
	MediaType   string
        Some other attributes ....
```
After adding some Printf's to the code and recompiling it , it found that the srcInfos variable contained the annotations , but the updatedSrcInfos didn't .

SrcInfos:
[srcInfos.txt](https://github.com/user-attachments/files/22059948/srcInfos.txt)

UpdatedSrcInfos:

[UpdatedSrcInfos.txt](https://github.com/user-attachments/files/22059953/UpdatedSrcInfos.txt)


So definetly something is going on in the LayersInfosForCopy , if we read it's implementation , which can be found in the storage/storage_src.go in the image repository.
[storage_src.go line 284 :](https://github.com/containers/image/blob/main/storage/storage_src.go#L284)
I'll let you discover the details of the implementation , but one part is definetly interesting for us .
```
		blobInfo := types.BlobInfo{
			Digest:    blobDigest,
			Size:      size,
			MediaType: uncompressedLayerType,
		}
		physicalBlobInfos = append(physicalBlobInfos, blobInfo)
		layerID = layer.Parent
	}
```
This part , which is located inside a for loop , will reconstruct the layers infos , starting from the top layer and then inverse them to get the correct order `	slices.Reverse(physicalBlobInfos) `.

But as you can see , the annotations are omitted , this why they are absent in the UpdatedSrcInfos .
Now , why does this happen with the containers-storage transport , meanwhile it doesn't occur when copying from a docker to docker transport directly , honestly not so sure since i didn't read that part from the source code (if you found why , i'd be more than happy to hear out).
Also why do we have this behaviour in the first place ? i don't know but i am sure the maintainers have valid reasons for that , let's hear from them.

**Comment by mtrmac** [comment]
Thanks for your report!

@GGh41th has correctly pointed at the relevant code — AFAICT this is overall a bug, the code intends to modify digests + MIME types, stripping annotations was not a goal.

**Comment by mtrmac** [comment]
@ver4a https://github.com/containers/container-libs/pull/299 should fix this — could you test that, and confirm that it handles everything relevant to your use case, please?

**Comment by ver4a** [comment]
I finally figured out how to use your fork. Thank you, it resolves this specific issue with missing annotations.

It didn't fix my use case, so that's apparently caused by something else that happens during copying, but that's a different issue.

**Comment by mtrmac** [comment]
Great, thanks for the confirmation. And I apologize I didn’t realize the repos are now in a bit of a flux with the switch to different module names, making the testing difficult.
